// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi3Lj_J8pHXBa7R60TffRiRm1fX1f8a-A',
    appId: '1:376835058558:web:c06a149851a9b3cb06a12f',
    messagingSenderId: '376835058558',
    projectId: 'tiki-app-eab31',
    authDomain: 'tiki-app-eab31.firebaseapp.com',
    storageBucket: 'tiki-app-eab31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA42TpZRfffUO9chXhAB3VDMj6Mg7PzZGY',
    appId: '1:376835058558:android:50bedfa59e61ce1406a12f',
    messagingSenderId: '376835058558',
    projectId: 'tiki-app-eab31',
    storageBucket: 'tiki-app-eab31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcmfTon78y6Ph1A-G0pFkbVPgH5bpJppE',
    appId: '1:376835058558:ios:7b6152daa80985e806a12f',
    messagingSenderId: '376835058558',
    projectId: 'tiki-app-eab31',
    storageBucket: 'tiki-app-eab31.appspot.com',
    iosClientId: '376835058558-fo492p9slovegsk619r8irpvqvu9p0qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcmfTon78y6Ph1A-G0pFkbVPgH5bpJppE',
    appId: '1:376835058558:ios:7b6152daa80985e806a12f',
    messagingSenderId: '376835058558',
    projectId: 'tiki-app-eab31',
    storageBucket: 'tiki-app-eab31.appspot.com',
    iosClientId: '376835058558-fo492p9slovegsk619r8irpvqvu9p0qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikiApp',
  );
}
